import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import CheckNetwork from '@/components/Common/CheckNextwork';
import Script from 'next/script'
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Chi cục thuế quận 8',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <head>
                <script src="https://cdn.ckeditor.com/4.17.2/standard/ckeditor.js"></script>
            </head>
            <body className={inter.className}>
                <div className="w-full">{children}</div>
                <CheckNetwork />
            </body>
        </html>
    );
}
