import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from './components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Chị cục thuế quận 8',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="flex justify-center">
                    <div className="flex flex-col w-[1200px]">
                        <Header />
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
